### ISSUE TITLE
new babel luatex-hyphenation loader clashes with polyglossia

### ISSUE THREAD

**Issue by u-fischer** [reutenauer/polyglossia#129]
The newest babel [2016/02/01 3.9o The Babel package] has changed the code to load hyphenation patterns for luatex. One obvious change is that the name of the command which stores if patterns have been loaded has changed in luababel.def: Instead of 

```
 \ifcsname lu@texhyphen@loaded@\the\language\endcsname
```

is it now

```
\@ifundefined{bbl@hyphendata@\the\language}%
```

This means that quite probably some of the tests in polyglossia are now wrong. At least one example of a clash has been already reported on tex.stackexchange:

http://tex.stackexchange.com/questions/291425/lualatex-and-polyglossia-with-setdefaultlanguagegerman-does-not-work-after-re

```
\documentclass[]{book}

\usepackage{polyglossia}
\setdefaultlanguage{german}


\begin{document}
Hallo Welt!

\end{document}

```

gives the error 

```
! You can't use `\relax' after \the.
<recently read> \l@german 

l.10 \begin{document}
```

**Comment by adunning** [comment]
Is Babel 3.9m still available anywhere? I had thought all was well and deleted my backup, only to discover this.

**Comment by reutenauer** [comment]
Many thanks for the report @u-fischer; unfortunately it is a little tricky to fix but I’m working on it.

@adunning, you can find any version of the TeX Live trees in the Subversion repository; [online](http://tug.org/svn/texlive/trunk/Master/) or with a Subversion client.  In this case you need `luababel.def` since that’s where the offending code is.

**Comment by adunning** [comment]
Thanks for looking at it! The version of Babel on CTAN has, in fact, been reverted to 3.9n.

**Comment by reutenauer** [comment]
Ah, OK.  Well, that’s probably best for the time being as Javier’s update was a little premature.

**Comment by adunning** [comment]
Babel 3.9q is now out, which is demonstrating the same problem.

**Comment by cdlm** [comment]
I'm getting a very similar error with 3.9n and latin (only backup `tlmgr` can revert to on my install). Overwriting `luababel.def` with an older snapshot from SVN doesn't seem to help…

**Comment by reutenauer** [comment]
I’m aware of the problem and expected it.  Javier updated Babel again without warning, so when I saw the CTAN announcement it was too late.  I don’t know why he does that.

I have a fix ready, I want to test it thoroughly and will come back to you later this week.  Thanks for all the reports.

**Comment by u-fischer** [comment]
The documentation of 3.9q contains in section 2 "Loading languages with language.dat"  a (temporary) workaround.

**Comment by reutenauer** [comment]
I’ve already got code that fixes that in the branch `issue-129` in this repository, but thanks.

**Comment by s9w** [comment]
Luatex+polyglossia with `\setmainlanguage{german}` still doesn't work for me. Is this correct? Anything new? This is quite a severe bug, is there any way to help?

**Comment by reutenauer** [comment]
Well, you can try and convince Javier Bezos to not make incompatible changes to Babel without any warning.  There is a bit of generic code in Babel for hyphenation pattern loading,  Polyglossia depends on it.  Also, testing is always important.

 But as already said, I have code in a branch that should fix most issues; I’ll make an emergency upload tonight and will try to improve the situation from there.

**Comment by reutenauer** [comment]
Actually, if you want to test, you can download [polyglossia.sty from that branch](https://github.com/reutenauer/polyglossia/blob/issue-129/tex/polyglossia.sty); the fix is rather messy but it should work.

**Comment by s9w** [comment]
OK. I'm no tex guru and wasn't aware that the issue was caused somewhere else.

With that polyglossia.sty, nothing works for me (neither english or german). Same error message for both:
```
! LuaTeX error [\directlua]:1: attempt to call field 'newloader' (a nil value)
stack traceback:
        [\directlua]:1: in main chunk.
\xpg@set@language@luatex@iv ...a.newloader('#1'))}
                                                  \language \directlua {tex....
l.6 }

?
! Emergency stop.
\xpg@set@language@luatex@iv ...a.newloader('#1'))}
                                                  \language \directlua {tex....
l.6 }
```

**Comment by reutenauer** [comment]
Sorry, you need `polyglossia.lua` from the same place.

It is expected that nothing works at all for Polyglossia and LuaTeX with the latest changes to Babel; any language will fail to load because TeX can’t find the hyphenation patterns.

**Comment by s9w** [comment]
That works great, thanks a lot!

Well, that sucks having to clean up others mess. I hope there will be better communication in the future.

**Comment by reutenauer** [comment]
Thanks for testing and thanks for the encouragements!  I’ll make the update tonight.

**Comment by simifilm** [comment]
I copied both mentioned files to my local tree, but this doesn't work. I get this rather peculiar error message: 

>File: gloss-german.ldf polyglossia: module for german
>
> FOO 1
> NOW I’M HERE
> FOO 2
> > \l@german=\relax.
> <recently read> \l@german 
>           
> l.6 }
>    
> ? 
> HELLO I’M HERE
> hyph-de-1901.pat.txt
> Language german was not yet loaded; created with id 4
> HELLO I’M HERE
> Language german already loaded; id is 4 DONE
> FOO 3
> FOO 4
> FOO 5
> 
> Package polyglossia Warning: You asked for `ngerman' but only `german' hyphenati
> on is available! on input line 68.

**Comment by reutenauer** [comment]
Sadly I no longer believe I have a good solution for all the problems the Babel changes introduced.  The code in the branch was still experimental and has got a little messy as you can see, so I recommend simply loading the minimal Babel data with `\usepackage[base]{babel}` before Polyglossia.  This basically adds the information that was removed from the format with the change in `hyphen.cfg`.  It’s ridiculous of course, and I’m still working on a long-term fix that doesn’t require Polyglossia users to load Babel, but for the time being this should work for everyone.

Another possibility would be to revert the recent changes to Babel, but that’s beyond my control.

**Comment by dohyunkim** [comment]
There seems to be no problem in compiling german language texts, when the macro `xpg@set@language@luatex@iv` in polyglossia.sty (around line 786) has been patched as follows:

```tex
\newcommand\xpg@set@language@luatex@iv[1]{%
  \ifluatex
    \xpg@check@ifdefined{#1}%
    \if@xpg@language@really@defined@\else
      \expandafter\chardef\csname l@#1\endcsname=\directlua{tex.sprint(polyglossia.newloader('#1'))}%
    \fi
    \language\csname l@#1\endcsname
  \fi
}
```

on top of current __master__ branch, which means that you have to copy gloss-german.ldf as well as polyglossia.{sty,lua} to the current working directory.

Once again, for `swissgerman` variant, gloss-german.ldf should be patched like the following around line 48:

```patch
--- /Users/nomosnomos/src/upload-texlive/polyglossia/tex/gloss-german.ldf       2016-03-18 09:32:03.000000000 +0900
+++ gloss-german.ldf    2016-03-22 11:09:20.000000000 +0900
@@ -45,10 +45,10 @@
          \@austrian@localefalse%
        \fi
        \ifx\@tmpa\tmp@swiss\@swiss@localetrue
-         \ifcsundef{l@swissgerman}%
+         \xpg@ifdefined{swissgerman}{}%
            {\xpg@warning{No hyphenation patterns were loaded for "Swiss German (Old Spelling)"\MessageBreak
              I will use the standard patterns for German (old spelling) instead}%
-           \adddialect\l@swissgerman\l@german\relax}{}%
+           \adddialect\l@swissgerman\l@german\relax}%
        \else
          \@swiss@localefalse%
        \fi}
```

though I did not checked other *.ldf files yet.

Certainly these patches might not be optimal, as it's not easy for me to understand the current polyglossia code because I am not familiar with etoolbox/xkeyval package macros. Anyway, it seems to work for me.

**Comment by reutenauer** [comment]
This is a step in the right direction, I just pushed these changes to master.  Many thanks @dohyunkim.  @simifilm, could you please test now, with [polyglossia.sty](https://github.com/reutenauer/polyglossia/blob/master/tex/polyglossia.sty), [polyglossia.lua](https://github.com/reutenauer/polyglossia/blob/master/tex/polyglossia.lua) and [gloss-german.ldf](https://github.com/reutenauer/polyglossia/blob/master/tex/gloss-german.ldf) from *master* (just follow links)?  @s9w, if you could confirm that it doesn’t introduce new problems for you that would be really great.

I completely agree that the code using macros from the packages `etoolbox.sty` and `xkeyval.sty` is a little confusing, @dohyunkim; most of it is not from me, actually, I inherited it from François Charette, the original author of Polyglossia.  The code for German is somewhat more confusing than the average; ironically that’s because François took great care to provide many options for the user!

**Comment by simifilm** [comment]
This does definitely improve the situation. `\setdefaultlanguage[spelling=new]{german}` seems to work now. What still does not work is `\setdefaultlanguage[latesthyphen,spelling=new]{german}` (which used to work).

**Comment by reutenauer** [comment]
Thank you @simifilm, that’s helpful.  I’ll fix `latesthyphen` (which was not part of my test cases; I’ll add it).  Note, however, that this option never had any real effect in Polyglossia, as there only is exactly one set of patterns available for the new spelling at any point in time: the latest if you’re running XeTeX or LuaTeX, or a frozen set of patterns dating from 1999 if you’re running pdfTeX or Knuth’s TeX.  Since Polyglossia is only usable with the former engines, you’ll always have the latest set of patterns.  This also holds true for the old spelling and the Swiss spelling, of course (and there always are exactly 6 sets of patterns for German in a recent TeX distribution, half of them frozen and the other half updated regularly).

But the option should of course not result in a error; I’ll fix that (we shouldn’t be too far now).

**Comment by dohyunkim** [comment]
I regret that I also have not tested `latesthyphen` option of gloss-german.ldf.
For this option to work, it seems that we have to add the following code into polyglossia.lua after loading language.dat.lua.

```lua
local newloader_available_languages = dofile(kpse.find_file('language.dat.lua'))
-- added next eight lines for synonyms
local t = {}
for k,v in pairs(newloader_available_languages) do
  t[k] = v
  for _,vv in pairs(v.synonyms) do
    t[vv] = v
  end
end
newloader_available_languages = t
```
with using gloss-german.ldf from `issue-129-latesthyphen-german` branch.

**Comment by dohyunkim** [comment]
just found a typo in gloss-german.ldf, line 48:
```diff
-	  \xpg@ifdefined{l@swissgerman}{}%
+	  \xpg@ifdefined{swissgerman}{}%
```

**Comment by reutenauer** [comment]
Thank you again, @dohyunkim!  I was hoping we could make the time difference work for us :-)

I have pushed both your suggested changes to the branch `issue-129-latesthyphen-german`; @simifilm, could you test and report if it works for you?  It doesn’t for me, but that’s another problem.

You’ll need [polyglossia.lua](https://github.com/reutenauer/polyglossia/blob/issue-129-latesthyphen-german/tex/polyglossia.lua) and [gloss-german.ldf](https://github.com/reutenauer/polyglossia/blob/issue-129-latesthyphen-german/tex/gloss-german.ldf) from that branch; [polyglossia.sty](https://github.com/reutenauer/polyglossia/blob/issue-129-latesthyphen-german/tex/polyglossia.sty) hasn’t changed since you last tested but you may download it again just to be sure.

**Comment by reutenauer** [comment]
For the record, the problem I’m having with the `latesthyphen` option has been introduced in two steps: pull request #122 in December added control sequences to record the list of loaded languages (useful to `tracklang.sty`, as I understand), but broke every language option except for the ones with the key `variant`; then [my fix for that](https://github.com/reutenauer/polyglossia/commit/d2a34ff) last month fixed most language options, but evidently not all of them.  Actually, now I look at my commit I see the problem very clearly, but I’m not sure how to correct it yet.

This is of course on top of the problems introduced by the Babel change.

**Comment by reutenauer** [comment]
I’ve pushed one more commit that should fix all the above; @simifilm, please test the branch `issue-129-latesthyphen-german` if you have the opportunity.

**Comment by s9w** [comment]
I tried the current code on the issue-129-latesthyphen-german branch and it works perfectly for me.

**Comment by simifilm** [comment]
There's still a problem for me. The following MWE

> \documentclass{article}
> \usepackage{polyglossia}
> \setdefaultlanguage[latesthyphen,spelling=new]{german}
> \begin{document}
> \end{document}

gives me

> Runaway argument?
> latesthyphen\relax \ifblank {spelling=new,} {\listbreak } {\etb@lst@docsvlist \
> ETC.
> ! File ended while scanning use of \xpg@parsekeyvalue.
> <inserted text> 
> \par 
> <*> poly.tex

**Comment by reutenauer** [comment]
Sorry @simifilm, I didn’t push my latest change (I’m on my work computer and ... oh, well).  It’s done now, you’ll need [polyglossia.sty](https://github.com/reutenauer/polyglossia/blob/issue-129-latesthyphen-german/tex/polyglossia.sty) in addition to the other two files.

Thanks to @s9w for testing too.

**Comment by simifilm** [comment]
I just run my test suite for my own `biblatex` style `biblatex-fiwi`, and it seems to work flawlessly. Thanks a lot.

**Comment by reutenauer** [comment]
Thank you, that’s a relief.  There’s one more of my use cases that is failing right now and I would like to try and fix it, but after that I think it’s actually for an upload.

**Comment by dohyunkim** [comment]
For _serbian_ language which has comma-separated list of hyphenation patterns and exceptions:
```lua
            if langdata.patterns and langdata.patterns ~= '' then
              for _,v in ipairs(langdata.patterns:explode ",+") do
                local pattfilepath = kpse.find_file(v)
                if pattfilepath then
                    local pattfile = io.open(pattfilepath)
                    lang.patterns(langobject, pattfile:read('*all'))
                    pattfile:close()
                end
              end
            end
            if langdata.hyphenation and langdata.hyphenation ~= '' then
              for _,v in ipairs(langdata.hyphenation:explode ",+") do
                local hyphfilepath = kpse.find_file(v)
                if hyphfilepath then
                    local hyphfile = io.open(hyphfilepath)
                    lang.hyphenation(langobject, hyphfile:read('*all'))
                    hyphfile:close()
                end
              end
            end
```

**Comment by reutenauer** [comment]
I just made an upload to CTAN that should fix all of the bugs mentioned in this issue.  There were more problems but I was running out of time.

I didn’t merge your code above, @dohyunkim, nor your pull request; I’ll get back to it shortly.

**Comment by reutenauer** [comment]
Note: the version of the code I pushed to CTAN is in branch `attempt-at-a-v1.42.4` and has the version number 1.42.4 – if rebasing hasn’t muddled up the repository too much.

**Comment by scottkosty** [comment]
Note that the fix for this bug may have (?) introduced a regression. See #163

**Comment by reutenauer** [comment]
Thank you for the report; I’ll look into that as explained in the comments to #163.

**Comment by jspitz** [comment]
What's the status of this? I think all issues are resolved, right?

**Comment by reutenauer** [comment]
Yes, all issues are resolved, although it would certainly be useful to review the code that was added in a hurry.  But for now, closing.  Thanks to everyone involved!
