### ISSUE TITLE
Polyglossia demands "Please define \devanagarifont with \newfontfamily" even if I use transliteration only.

### ISSUE THREAD

**Issue by ppasedach** [reutenauer/polyglossia#183]
I would like to use polyglossia for switching between hyphenation rules for English and Sanskrit, without needing to do any specific font setup for it: 

```
\documentclass{article}
\usepackage{polyglossia}
\setdefaultlanguage{english}
\setotherlanguage{sanskrit}
\setotherlanguage{german}
\begin{document}
Something.
\textgerman{Etwas.}
\textsanskrit{kiṃcit.}
\end{document}

```
gives me the following error message:
```
! Package polyglossia Error: The current roman font does not contain the Devanagari script!
(polyglossia)                Please define \devanagarifont with \newfontfamily.
```

Of course I can follow the instruction in the error message and define a `\devanagarifont`, but if I'm intending to use latin transliteration of Sanskrit only this should not be necessary. Apparently if none of the other (indic) script options present in `gloss-sanskrit.ldf` is specifically selected,  an option for transliteration not given, Devanagari is assumed as a default? `hyph-sa.tex` used by `polyglossia` for the hyphenation patterns is handling transliterated Sanskrit well. 

Related also [this thread](http://tug.org/pipermail/xetex/2017-February/026998.html), and this [comment](https://tex.stackexchange.com/questions/271703/adding-default-hyphenation-for-transliterated-sanskrit#comment655741_271703) here.

**Comment by jspitz** [comment]
This is fixed in current master (as opposed to 1.44).

Someone who can please close this ticket.

**Comment by ppasedach** [comment]
In current TeX Live 2020 I still get this. polyglossia 2020/04/08 v1.49 .

**Comment by jspitz** [comment]
To clarify:

You need to use the `script=Latin` option (see `polyglossia` manual):
```tex
\documentclass{article}
\usepackage{polyglossia}
\setdefaultlanguage{english}
\setotherlanguage[script=Latin]{sanskrit}
\setotherlanguage{german}
\begin{document}
Something.
\textgerman{Etwas.}
\textsanskrit{kiṃcit.}
\end{document}
```

The default script of Sanskrit still is (and remains) Devanagari.
