### ISSUE TITLE
Issue with period in headings number (RTL languages)

### ISSUE THREAD

**Issue by seloumi** [reutenauer/polyglossia#213]
Consider this example of writing  arabic headings with tableofcontents 
```latex
\documentclass{article}
\usepackage{polyglossia}
\setdefaultlanguage[numerals=maghrib]{arabic}
\newfontfamily\arabicfont[Script=Arabic]{Amiri}

\begin{document}

\tableofcontents

\section{عنوان أول}
\subsection{عنوان فرعي أول}
\subsection{عنوان فرعي ثان}
\section{عنوان ثان}
1.23
\end{document}
```
Which produce 

![capture](https://user-images.githubusercontent.com/8249073/48113073-79e7c800-e259-11e8-8442-b1d48779b448.PNG)

Numbers with period in headings are reversed, this is due to a code from `bidi` package which invert nembers containing a period but this is not  desirable inside headings numbers. 

A solution for this issue  is to add  `\setnonlatin` from bidi like this

```latex
\documentclass{article}
\usepackage{polyglossia}
\setdefaultlanguage[numerals=maghrib]{arabic}
\newfontfamily\arabicfont[Script=Arabic]{Amiri}

\setnonlatin

\begin{document}

\tableofcontents

\section{عنوان أول}
\subsection{عنوان فرعي أول}
\subsection{عنوان فرعي ثان}
\section{عنوان ثان}
1.23
\end{document}
```

My request is adding this solution when an RTL language is defined as main language, thanks a lot.

**Comment by seloumi** [comment]
No reply !!!

**Comment by jspitz** [comment]
@seloumi can you please try if the following change in gloss-arabic produces the correct result in- and outside headings?

```
\def\arabicnumber#1{%
  \ifeastern@numerals
    \arabicdigits{\number#1}%
  \else
    \RL{\number#1}%
  \fi}
```

Just replace the existing `\arabicnumber` definition with this.

**Comment by jspitz** [comment]
or even better
```
\def\arabicnumber#1{%
  \ifeastern@numerals
    \arabicdigits{\number#1}%
  \else
    \@ensure@dir{\number#1}%
  \fi}
```

**Comment by seloumi** [comment]
Yes this solve the problem

**Comment by jspitz** [comment]
Thanks for testing. Fixed.

**Comment by seloumi** [comment]
But for `mashriq` option of numerals the issue still exists
```latex
\documentclass{article}
\usepackage{polyglossia}
\setdefaultlanguage[numerals=mashriq]{arabic}
\newfontfamily\arabicfont[Script=Arabic]{Amiri}

\begin{document}

\tableofcontents

\section{عنوان أول}
\subsection{عنوان فرعي أول}
\subsection{عنوان فرعي ثان}
\section{عنوان ثان}
١.٢٣
\end{document}
```

![image](https://user-images.githubusercontent.com/8249073/64076258-da516580-ccc2-11e9-96dc-30e7b9f1da3f.png)

**Comment by seloumi** [comment]
I think the issue can be solved either for `maghrib` or `mashriq` form with 
```
\def\arabicnumber#1{%
\ifeastern@numerals
\@ensure@dir{\arabicdigits{\number#1}}%
\else
\@ensure@dir{\number#1}%
\fi}
```

**Comment by jspitz** [comment]
OK, done.

**Comment by seloumi** [comment]
Thanks a lot

**Comment by jspitz** [comment]
I've reverted the fixes. It turned out \set[non]latin is the way to go.

See https://github.com/bidi-tex/bidi/issues/5

**Comment by jspitz** [comment]
Re-fixed with `\setlatin`/`\setnonlatin`.
@seloumi please test.

**Comment by seloumi** [comment]
This solve the issue but another problem appear with `numerals=maghrib` numbering of equation still in mashriq form !
There are also warnings  of hyphenation from latex-gloss.sty 
```latex
\documentclass{article}
\usepackage{amsmath}
\usepackage{polyglossia}
\setdefaultlanguage[numerals=maghrib]{arabic}
\newfontfamily\arabicfont[Script=Arabic]{Amiri}

\begin{document}

\tableofcontents

\section{عنوان أول}
\subsection{عنوان فرعي أول}
\subsection{عنوان فرعي ثان}
\section{عنوان ثان}

\begin{equation}
a=\frac{dx}{dt}
\end{equation}

\end{document}
```

![Capture](https://user-images.githubusercontent.com/8249073/64167157-eb2be380-ce48-11e9-806d-50af5fb7f968.JPG)

**Comment by jspitz** [comment]
> @jspitz This solve the issue but another problem appear with `numerals=maghrib` numbering of equation still in mashriq form !

Fixed.

> There are also warnings of hyphenation from latex-gloss.sty

Yes, this is known.

**Comment by seloumi** [comment]
@jspitz with version 1.45 the issue persists for eastern numerals form (numbers for subsection heading still reversed)

```latex
\documentclass[12pt]{article}
\usepackage{polyglossia}
\setdefaultlanguage{arabic}
\newfontfamily\arabicfont[Script=Arabic]{Amiri}

\begin{document}

\section{عنوان}
\subsection{عنوان فرعي أول}
\subsection{عنوان فرعي ثاني}

\end{document}
```

![image](https://user-images.githubusercontent.com/8249073/67900240-5d2c5a80-fb64-11e9-96e1-d006d277a086.png)

**Comment by jspitz** [comment]
Should be fixed at 4eb6cf56a146. Please test.

**Comment by bykhov** [comment]
Since I have recently updated to 1.46, I have problems in Hebrew text with ordinary numbers when both numbers with period and section numbering with period reverted. Example follows.

    \documentclass[12pt]{article}
    \usepackage{polyglossia,bidi}
    \setmainlanguage{hebrew}
    \setotherlanguage{english}
    \setmainfont{David}
    \setmonofont{Courier New}
    \begin{document}
     בדיקה 1.23
    \begin{english}
    Test 1.23
    \end{english}
    \section{א}
    \subsection{א}
    \subsection{א}
    \end{document}
![image](https://user-images.githubusercontent.com/4847480/71675821-54841a80-2d87-11ea-99d7-a2d88e69205c.png)

See also [bidi-tex/bidi#11](https://github.com/bidi-tex/bidi/issues/11)

**Comment by jspitz** [comment]
Thanks, this should be fixed in 4c3eb54ab6856e

**Comment by bykhov** [comment]
Thanks, it has fixed English text. However, Hebrew one and section numbering are still reverted.
![image](https://user-images.githubusercontent.com/4847480/71683105-4986b580-2d9a-11ea-9fb0-9296bba79b75.png)

**Comment by jspitz** [comment]
And they shouldn't? If so, this needs to be fixed in gloss-hebrew.

**Comment by jspitz** [comment]
Please try after 038ba03830

**Comment by jspitz** [comment]
> Please try after [038ba03](https://github.com/reutenauer/polyglossia/commit/038ba0383019c2e232128a3188030a303b1e17ad)

No, this does not work.

**Comment by seloumi** [comment]
@jspitz  I thought the numbering in headings for all RTL languages  should be RTL ! 
Since all numbers need to be LTR in hebrew I think a \setlatin  command at the beginning is sufficient to solve the issue.

**Comment by jspitz** [comment]
> @jspitz I thought the numbering in headings for all RTL languages should be RTL !
> Since all numbers need to be LTR in hebrew I think a `\setlatin` command at the beginning is sufficient to solve the issue.

But doesn't this re-introduce issues with Arabic?

**Comment by bykhov** [comment]
> Since all numbers need to be LTR in hebrew I think a \setlatin command at the beginning is sufficient to solve the issue.

Excellent with Hebrew!!!
![image](https://user-images.githubusercontent.com/4847480/71685730-de40e180-2da1-11ea-841e-db85b221dfd0.png)
Unfortunately, I don't know about Arabic.

**Comment by seloumi** [comment]
`\setlatin` can't be added in gloss-hebrew?

**Comment by jspitz** [comment]
> `\setlatin` can't be added in gloss-hebrew?

No, only globally for all RLL languages or not.

**Comment by jspitz** [comment]
Please try 57b17b3a710a

**Comment by seloumi** [comment]
Also with `\setlatin` parentheses for equation  numbering in RTL context become inverted.

**Comment by jspitz** [comment]
`\setlatin` is semantically wrong for Hebrew, as Hebrew is not an LTR script (and this is how the Latin conditional is defined). The only issue is with numbers, and this is now worked around in `gloss-hebrew`. The general problem is that the bidi package is very much focused on Arabic script (as opposed to other RTL scripts).

**Comment by bykhov** [comment]
> Please try after [038ba03](https://github.com/reutenauer/polyglossia/commit/038ba0383019c2e232128a3188030a303b1e17ad)

> Also with `\setlatin` parentheses for equation numbering in RTL context become inverted.


This is how it works now with equation numbering and `\setlatin`. It looks exactly how it is supposed to be.

```
\documentclass[12pt,leqno]{article}

\usepackage{amsmath}
\usepackage{polyglossia,bidi}
\setmainlanguage{hebrew}
\setotherlanguage{english}
\setmainfont{David}
\setmonofont{Courier New}
\setlatin
%fix equation numbering for formulas
\makeatletter
\def\tagform@#1{\maketag@@@{(\ignorespaces#1\unskip)}}
\makeatother
\begin{document}
בדיקה 1.23

\begin{english}
Test 1.23
\end{english}

\section{א}
\subsection{א}
\subsection{א}
משוואה \eqref{eq}
\begin{equation}\label{eq}
A = \sin(x)
\end{equation}
\end{document}
```

![image](https://user-images.githubusercontent.com/4847480/71686824-f2d2a900-2da4-11ea-8873-144ec7efbe7f.png)

**Comment by jspitz** [comment]
Can you please try after try after 038ba03 without `\setlatin` and your formula numbering tweak? It should not be needed

**Comment by bykhov** [comment]
> Can you please try after try after [038ba03](https://github.com/reutenauer/polyglossia/commit/038ba0383019c2e232128a3188030a303b1e17ad) without `\setlatin` and your formula numbering tweak? It should not be needed



Without `\setlatin` the problem is with numbering inside Hebrew text and sections.
![image](https://user-images.githubusercontent.com/4847480/71778686-8aa8e080-2fb9-11ea-9502-303f4f33645d.png)

With  `\setlatin` fixes the problem above and arise the problem with numbering of equations (parenthesis).
![image](https://user-images.githubusercontent.com/4847480/71778711-e1aeb580-2fb9-11ea-8f99-797a8bdfbf77.png)



> Please try [57b17b3](https://github.com/reutenauer/polyglossia/commit/57b17b3a710a3f5b721caa40c15ba5b042c8ec86)

Seem to work perfect without `\setlatin`.
![image](https://user-images.githubusercontent.com/4847480/71778807-29820c80-2fbb-11ea-8b22-c7e6a94ec2a5.png)

```
\documentclass[12pt,leqno]{article}

\usepackage{amsmath}
\usepackage{polyglossia,bidi}
\setmainlanguage{hebrew}
\setotherlanguage{english}
\setmainfont{David}
\setmonofont{Courier New}
\begin{document}
בדיקה 1.23
\begin{english}
Test 1.23
\end{english}
\section{א}
\subsection{א}
\subsection{א}
משוואה \eqref{eq}, 
\eqref{eq1}
\begin{subequations}\label{eq1}
\begin{align}
A &= \cos(x) \label{eq}\\
V &= \cos(x)
\end{align}
\end{subequations}
\appendix
\section{בדיקה}
\subsection{בדיקה}
\end{document}
```

**Comment by jspitz** [comment]
It turned out `\ensure@LTR` was needed with Eastern Arabic numerals rather than `\ensure@dir` to get the proper direction with LuaTeX (XeTeX is unaffected). This has been fixed for 1.63 for Arabic, Kurdish, Persian, Syriac, and Urdu in the abovementioned two commits.
