### ISSUE TITLE
Error when loading Hungarian language

### ISSUE THREAD

**Issue by Drkazmer** [reutenauer/polyglossia#388]
I get errors when loading Hungarian language using the following piece of code:

```
\documentclass[a4paper,12pt,twoside]{article}
\usepackage[margin=2.5cm]{geometry}
\usepackage{polyglossia}
\setmainlanguage{hungarian}
\begin{document}
Példa.
\end{document}
```

See also on TeX SE: https://tex.stackexchange.com/questions/526213/hungarian-polyglossia-error

**Comment by eg9** [comment]
See the fix in https://tex.stackexchange.com/a/526218/4427

**Comment by jspitz** [comment]
This should actually be fixed in polyglossia 1.47 which has been released to CTAN yesterday,

**Comment by jspitz** [comment]
For the record this is a duplicate of #373. The fix was pushed at 902dabaec296.

**Comment by Drkazmer** [comment]
@jspitz In the MikTeX package browser I still see 1.46. Should I do something to have the new version?

**Comment by jspitz** [comment]
You probably need to wait until MikTeX catches up.
