### ISSUE TITLE
problem in gloss-ukrainian.ldf with alphabetic numbering

### ISSUE THREAD

**Issue by dsavchenko** [reutenauer/polyglossia#440]
Consider minimal example
```
\documentclass{book}
\usepackage{fontspec}
\usepackage{polyglossia}
\setmainlanguage{ukrainian}
\setmainfont[Ligatures=TeX]{Liberation Serif}
\newfontfamily{\cyrillicfontsf}{Liberation Serif}

\begin{document}

\chapter{Розділ}
Текст українською

\appendix
\chapter{Додаток}
Текст

\end{document}
```
Compiling this code with xelatex ends up in error 
```
! Undefined control sequence.
\thechapter ->\@Alph 
                     \c@chapter 
l.14 \chapter{Додаток}
```
and the appendix number left empty.

**Comment by jspitz** [comment]
Schould be fixed at f67bd83bdcd4b. Please test.

**Comment by dsavchenko** [comment]
It works now. Thanks!

**Comment by jspitz** [comment]
Please keep opened until the fix is released.

**Comment by dsavchenko** [comment]
Sorry, I have just realised that the default numerals for appendices are now arabic. For numerals=cyrillic-alph (which I expected to be the default for the Ukrainian language) the problem still exists.

**Comment by jspitz** [comment]
Please try again after 00699dd285c

**Comment by dsavchenko** [comment]
Great! Now it works with both options.
