### ISSUE TITLE
with XeTeX: warning: File gloss-latex.ldf does not exist!

### ISSUE THREAD

**Issue by FreeInMind** [reutenauer/polyglossia#537]
I use 

 - XeTeX 3.141592653-2.6-0.999994 (TeX Live 2022)
 - kpathsea version 6.3.4

to compile

```
    \documentclass[a4paper]{scrartcl}
    \usepackage{xltxtra}
    \usepackage{polyglossia}
    \setdefaultlanguage{de}
    
    \begin{document}
     Test
    \end{document}
```

I got two warnings:

    Package polyglossia Warning: File gloss-latex.ldf does not exist!
    (polyglossia)                I will nevertheless try to use hyphenation pattern
    s for latex. on input line 2549.
    
    
```
    Package polyglossia Warning: No hyphenation patterns were loaded for `latex'
    (polyglossia)                I will use \language=\l@nohyphenation instead on i
    nput line 2549.
```

What has happened? What can I do to avoid these warnings?

Complete log
```

    *****
    *****     XeLaTeX Ausgabe: 
    *****     cd "/home/ro/Schreibtisch/wegtex"
    *****     xelatex -interaction=nonstopmode -synctex=1 -enable-write18 test.tex
    *****
    This is XeTeX, Version 3.141592653-2.6-0.999994 (TeX Live 2022) (preloaded format=xelatex)
     \write18 enabled.
    entering extended mode
    (./test.tex
    LaTeX2e <2021-11-15> patch level 1
    L3 programming layer <2022-02-24>
    (/usr/local/texlive/2022/texmf-dist/tex/latex/koma-script/scrartcl.cls
    Document Class: scrartcl 2021/11/13 v3.35 KOMA-Script document class (article)
    (/usr/local/texlive/2022/texmf-dist/tex/latex/koma-script/scrkbase.sty
    (/usr/local/texlive/2022/texmf-dist/tex/latex/koma-script/scrbase.sty
    (/usr/local/texlive/2022/texmf-dist/tex/latex/koma-script/scrlfile.sty
    (/usr/local/texlive/2022/texmf-dist/tex/latex/koma-script/scrlfile-hook.sty
    (/usr/local/texlive/2022/texmf-dist/tex/latex/koma-script/scrlogo.sty)))
    (/usr/local/texlive/2022/texmf-dist/tex/latex/graphics/keyval.sty)))
    (/usr/local/texlive/2022/texmf-dist/tex/latex/koma-script/tocbasic.sty)
    (/usr/local/texlive/2022/texmf-dist/tex/latex/koma-script/scrsize11pt.clo)
    (/usr/local/texlive/2022/texmf-dist/tex/latex/koma-script/typearea.sty))
    (/usr/local/texlive/2022/texmf-dist/tex/xelatex/xltxtra/xltxtra.sty
    (/usr/local/texlive/2022/texmf-dist/tex/generic/iftex/ifluatex.sty
    (/usr/local/texlive/2022/texmf-dist/tex/generic/iftex/iftex.sty))
    (/usr/local/texlive/2022/texmf-dist/tex/generic/iftex/ifxetex.sty)
    (/usr/local/texlive/2022/texmf-dist/tex/latex/fontspec/fontspec.sty
    (/usr/local/texlive/2022/texmf-dist/tex/latex/l3packages/xparse/xparse.sty
    (/usr/local/texlive/2022/texmf-dist/tex/latex/l3kernel/expl3.sty
    (/usr/local/texlive/2022/texmf-dist/tex/latex/l3backend/l3backend-xetex.def
    (|extractbb --version))))
    (/usr/local/texlive/2022/texmf-dist/tex/latex/fontspec/fontspec-xetex.sty
    (/usr/local/texlive/2022/texmf-dist/tex/latex/base/fontenc.sty)
    (/usr/local/texlive/2022/texmf-dist/tex/latex/fontspec/fontspec.cfg)))
    (/usr/local/texlive/2022/texmf-dist/tex/latex/realscripts/realscripts.sty)
    (/usr/local/texlive/2022/texmf-dist/tex/latex/metalogo/metalogo.sty
    (/usr/local/texlive/2022/texmf-dist/tex/latex/graphics/graphicx.sty
    (/usr/local/texlive/2022/texmf-dist/tex/latex/graphics/graphics.sty
    (/usr/local/texlive/2022/texmf-dist/tex/latex/graphics/trig.sty)
    (/usr/local/texlive/2022/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
    (/usr/local/texlive/2022/texmf-dist/tex/latex/graphics-def/xetex.def)))))
    (/usr/local/texlive/2022/texmf-dist/tex/latex/polyglossia/polyglossia.sty
    (/usr/local/texlive/2022/texmf-dist/tex/latex/etoolbox/etoolbox.sty)
    (/usr/local/texlive/2022/texmf-dist/tex/latex/makecmds/makecmds.sty)
    (/usr/local/texlive/2022/texmf-dist/tex/latex/xkeyval/xkeyval.sty
    (/usr/local/texlive/2022/texmf-dist/tex/generic/xkeyval/xkeyval.tex
    (/usr/local/texlive/2022/texmf-dist/tex/generic/xkeyval/xkvutils.tex)))
    (/usr/local/texlive/2022/texmf-dist/tex/latex/l3packages/l3keys2e/l3keys2e.sty)
    
    Package polyglossia Warning: File gloss-latex.ldf does not exist!
    (polyglossia)                I will nevertheless try to use hyphenation pattern
    s for latex. on input line 2549.
    
    
    Package polyglossia Warning: No hyphenation patterns were loaded for `latex'
    (polyglossia)                I will use \language=\l@nohyphenation instead on i
    nput line 2549.
    
    ) (/usr/local/texlive/2022/texmf-dist/tex/latex/polyglossia/gloss-de.ldf
    (/usr/local/texlive/2022/texmf-dist/tex/latex/polyglossia/gloss-german.ldf
    (/usr/local/texlive/2022/texmf-dist/tex/latex/polyglossia/babelsh.def)))
    (./test.aux) (/usr/local/texlive/2022/texmf-dist/tex/latex/base/ts1cmr.fd)
    [1] (./test.aux) )
    Output written on test.pdf (1 page).
    SyncTeX written on test.synctex.gz.
    Transcript written on test.log.

```

**Comment by maaattes** [comment]
I'm facing the same problem with LuaTeX after upgrading to TeX Live 2022. :confused:

**Comment by jspitz** [comment]
Yes, the new file extension *.lde introduced in 87323f259d47 has been forgotten to be added at the build script, so `latex.lde` is missing from the release. You can dosnload it from here for the time being:
https://github.com/reutenauer/polyglossia/raw/master/tex/gloss-latex.lde

I'll fix the problem soon.

**Comment by jspitz** [comment]
Polyglossia 1.55 has just been submitted to CTAN. It should fix the issue.

**Comment by maaattes** [comment]
Sorry, but I'm still having some issues. Using `polyglossia` 2022/04/09 v1.55.

```latex
\documentclass[a4paper]{scrartcl}
\usepackage[babelshorthands=true]{polyglossia}
\setdefaultlanguage{english}
\setotherlanguage{german}

\begin{document}

This is a test of issue nr 537.

% works
\textgerman{Dies ist ein Test von Problem-""Nr. 537.}

\textlang{german}{Dies ist ein Test von Problem-""Nr. 537.}

\begin{otherlanguage}{german}
Dies ist ein Test von Problem-""Nr. 537.
\end{otherlanguage}{german}

% does not work
\foreignlanguage{german}{Dies ist ein Test von Problem-""Nr. 537.}

\end{document}
```

<details>
  <summary>Log file</summary>
  
  ```console
  This is LuaHBTeX, Version 1.15.0 (TeX Live 2022)  (format=lualatex 2022.4.8)  9 APR 2022 16:03
  system commands enabled.
  **/home/mattes/texexample/mwe12.tex
  (/home/mattes/texexample/mwe12.tex
  LaTeX2e <2021-11-15> patch level 1
  Lua module: luaotfload 2022-03-18 3.21 Lua based OpenType font support
  Lua module: lualibs 2021-05-20 2.74 ConTeXt Lua standard libraries.
  Lua module: lualibs-extended 2021-05-20 2.74 ConTeXt Lua libraries -- extended c
  ollection.
  luaotfload | conf : Root cache directory is "/home/mattes/.texlive2022/texmf-var
  /luatex-cache/generic/names".
  luaotfload | init : Loading fontloader "fontloader-2022-02-24.lua" from kpse-res
  olved path "/usr/local/texlive/2022/texmf-dist/tex/luatex/luaotfload/fontloader-
  2022-02-24.lua".
  Lua-only attribute luaotfload@noligature = 1
  luaotfload | init : Context OpenType loader version 3.119
  Inserting `luaotfload.node_processor' at position 1 in `pre_linebreak_filter'.
  Inserting `luaotfload.node_processor' at position 1 in `hpack_filter'.
  Inserting `luaotfload.glyph_stream' at position 1 in `glyph_stream_provider'.
  Inserting `luaotfload.define_font' at position 1 in `define_font'.
  Lua-only attribute luaotfload_color_attribute = 2
  luaotfload | conf : Root cache directory is "/home/mattes/.texlive2022/texmf-var
  /luatex-cache/generic/names".
  Inserting `luaotfload.harf.strip_prefix' at position 1 in `find_opentype_file'.
  Inserting `luaotfload.harf.strip_prefix' at position 1 in `find_truetype_file'.
  Removing  `luaotfload.glyph_stream' from `glyph_stream_provider'.
  Inserting `luaotfload.harf.glyphstream' at position 1 in `glyph_stream_provider'
  .
  Inserting `luaotfload.harf.finalize_vlist' at position 1 in `post_linebreak_filt
  er'.
  Inserting `luaotfload.harf.finalize_hlist' at position 2 in `hpack_filter'.
  Inserting `luaotfload.cleanup_files' at position 1 in `wrapup_run'.
  Inserting `luaotfload.harf.finalize_unicode' at position 1 in `finish_pdffile'.
  Inserting `luaotfload.glyphinfo' at position 1 in `glyph_info'.
  Lua-only attribute luaotfload.letterspace_done = 3
  Inserting `luaotfload.aux.set_sscale_dimens' at position 1 in `luaotfload.patch_
  font'.
  Inserting `luaotfload.aux.set_font_index' at position 2 in `luaotfload.patch_fon
  t'.
  Inserting `luaotfload.aux.patch_cambria_domh' at position 3 in `luaotfload.patch
  _font'.
  Inserting `luaotfload.aux.fixup_fontdata' at position 1 in `luaotfload.patch_fon
  t_unsafe'.
  Inserting `luaotfload.aux.set_capheight' at position 4 in `luaotfload.patch_font
  '.
  Inserting `luaotfload.aux.set_xheight' at position 5 in `luaotfload.patch_font'.
  Inserting `luaotfload.rewrite_fontname' at position 6 in `luaotfload.patch_font'
  . L3 programming layer <2022-02-24>
  Inserting `tracingstacklevels' at position 1 in `input_level_string'.
  (/usr/local/texlive/2022/texmf-dist/tex/latex/koma-script/scrartcl.cls
  Document Class: scrartcl 2021/11/13 v3.35 KOMA-Script document class (article)
  (/usr/local/texlive/2022/texmf-dist/tex/latex/koma-script/scrkbase.sty
  Package: scrkbase 2021/11/13 v3.35 KOMA-Script package (KOMA-Script-dependent b
  asics and keyval usage)
  
  (/usr/local/texlive/2022/texmf-dist/tex/latex/koma-script/scrbase.sty
  Package: scrbase 2021/11/13 v3.35 KOMA-Script package (KOMA-Script-independent 
  basics and keyval usage)
  
  (/usr/local/texlive/2022/texmf-dist/tex/latex/koma-script/scrlfile.sty
  Package: scrlfile 2021/11/13 v3.35 KOMA-Script package (file load hooks)
  
  (/usr/local/texlive/2022/texmf-dist/tex/latex/koma-script/scrlfile-hook.sty
  Package: scrlfile-hook 2021/11/13 v3.35 KOMA-Script package (using LaTeX hooks)
  
  
  (/usr/local/texlive/2022/texmf-dist/tex/latex/koma-script/scrlogo.sty
  Package: scrlogo 2021/11/13 v3.35 KOMA-Script package (logo)
  )))
  (/usr/local/texlive/2022/texmf-dist/tex/latex/graphics/keyval.sty
  Package: keyval 2014/10/28 v1.15 key=value parser (DPC)
  \KV@toks@=\toks16
  )
  Applying: [2021/05/01] Usage of raw or classic option list on input line 252.
  Already applied: [0000/00/00] Usage of raw or classic option list on input line
  368.
  ))
  (/usr/local/texlive/2022/texmf-dist/tex/latex/koma-script/tocbasic.sty
  Package: tocbasic 2021/11/13 v3.35 KOMA-Script package (handling toc-files)
  \scr@dte@tocline@numberwidth=\skip47
  \scr@dte@tocline@numbox=\box50
  )
  Package tocbasic Info: babel extension for `toc' omitted
  (tocbasic)             because of missing \bbl@set@language on input line 135.
  Class scrartcl Info: File `scrsize11pt.clo' used instead of
  (scrartcl)           file `scrsize11.clo' to setup font sizes on input line 224
  2.
  
  (/usr/local/texlive/2022/texmf-dist/tex/latex/koma-script/scrsize11pt.clo
  File: scrsize11pt.clo 2021/11/13 v3.35 KOMA-Script font size class option (11pt
  )
  luaotfload | db : Font names database loaded from /home/mattes/.texlive2022/texm
  f-var/luatex-cache/generic/names/luaotfload-names.luc.gz)
  (/usr/local/texlive/2022/texmf-dist/tex/latex/koma-script/typearea.sty
  Package: typearea 2021/11/13 v3.35 KOMA-Script package (type area)
  \ta@bcor=\skip48
  \ta@div=\count183
  Package typearea Info: You've used standard option `a4paper'.
  (typearea)             This is correct!
  (typearea)             Internally I'm using `paper=a4'.
  (typearea)             If you'd like to set the option with \KOMAoptions,
  (typearea)             you'd have to use `paper=a4' there
  (typearea)             instead of `a4paper', too.
  \ta@hblk=\skip49
  \ta@vblk=\skip50
  \ta@temp=\skip51
  \footheight=\skip52
  Package typearea Info: These are the values describing the layout:
  (typearea)             DIV  = 10
  (typearea)             BCOR = 0.0pt
  (typearea)             \paperwidth      = 597.50793pt
  (typearea)              \textwidth      = 418.25555pt
  (typearea)              DIV departure   = -6%
  (typearea)              \evensidemargin = 17.3562pt
  (typearea)              \oddsidemargin  = 17.3562pt
  (typearea)             \paperheight     = 845.04694pt
  (typearea)              \textheight     = 595.80026pt
  (typearea)              \topmargin      = -25.16531pt
  (typearea)              \headheight     = 17.0pt
  (typearea)              \headsep        = 20.40001pt
  (typearea)              \topskip        = 11.0pt
  (typearea)              \footskip       = 47.6pt
  (typearea)              \baselineskip   = 13.6pt
  (typearea)              on input line 1743.
  )
  \c@part=\count184
  \c@section=\count185
  \c@subsection=\count186
  \c@subsubsection=\count187
  \c@paragraph=\count188
  \c@subparagraph=\count189
  \scr@dte@section@maxnumwidth=\skip53
  Class scrartcl Info: using compatibility default `runin=bysign'
  (scrartcl)           for `\section on input line 4852.
  Class scrartcl Info: using compatibility default `afterindent=bysign'
  (scrartcl)           for `\section on input line 4852.
  \scr@dte@part@maxnumwidth=\skip54
  Class scrartcl Info: using compatibility default `afterindent=false'
  (scrartcl)           for `\part on input line 4860.
  \scr@dte@subsection@maxnumwidth=\skip55
  Class scrartcl Info: using compatibility default `runin=bysign'
  (scrartcl)           for `\subsection on input line 4870.
  Class scrartcl Info: using compatibility default `afterindent=bysign'
  (scrartcl)           for `\subsection on input line 4870.
  \scr@dte@subsubsection@maxnumwidth=\skip56
  Class scrartcl Info: using compatibility default `runin=bysign'
  (scrartcl)           for `\subsubsection on input line 4880.
  Class scrartcl Info: using compatibility default `afterindent=bysign'
  (scrartcl)           for `\subsubsection on input line 4880.
  \scr@dte@paragraph@maxnumwidth=\skip57
  Class scrartcl Info: using compatibility default `runin=bysign'
  (scrartcl)           for `\paragraph on input line 4891.
  Class scrartcl Info: using compatibility default `afterindent=bysign'
  (scrartcl)           for `\paragraph on input line 4891.
  \scr@dte@subparagraph@maxnumwidth=\skip58
  Class scrartcl Info: using compatibility default `runin=bysign'
  (scrartcl)           for `\subparagraph on input line 4901.
  Class scrartcl Info: using compatibility default `afterindent=bysign'
  (scrartcl)           for `\subparagraph on input line 4901.
  \abovecaptionskip=\skip59
  \belowcaptionskip=\skip60
  \c@pti@nb@sid@b@x=\box51
  Package tocbasic Info: babel extension for `lof' omitted
  (tocbasic)             because of missing \bbl@set@language on input line 6076.
  
  \scr@dte@figure@maxnumwidth=\skip61
  \c@figure=\count190
  Package tocbasic Info: babel extension for `lot' omitted
  (tocbasic)             because of missing \bbl@set@language on input line 6091.
  
  \scr@dte@table@maxnumwidth=\skip62
  \c@table=\count191
  Class scrartcl Info: Redefining `\numberline' on input line 6258.
  \bibindent=\dimen137
  )
  (/home/mattes/texmf/tex/latex/polyglossia/polyglossia.sty
  Package: polyglossia 2022/04/09 v1.55 Modern multilingual typesetting with XeLa
  TeX and LuaLaTeX
  
  (/usr/local/texlive/2022/texmf-dist/tex/latex/etoolbox/etoolbox.sty
  Package: etoolbox 2020/10/05 v2.5k e-TeX tools for LaTeX (JAW)
  \etb@tempcnta=\count192
  )
  (/usr/local/texlive/2022/texmf-dist/tex/latex/makecmds/makecmds.sty
  Package: makecmds 2009/09/03 v1.0a extra command making commands
  )
  (/usr/local/texlive/2022/texmf-dist/tex/latex/xkeyval/xkeyval.sty
  Package: xkeyval 2020/11/20 v2.8 package option processing (HA)
  
  (/usr/local/texlive/2022/texmf-dist/tex/generic/xkeyval/xkeyval.tex
  (/usr/local/texlive/2022/texmf-dist/tex/generic/xkeyval/xkvutils.tex
  \XKV@toks=\toks17
  \XKV@tempa@toks=\toks18
  )
  \XKV@depth=\count193
  File: xkeyval.tex 2014/12/03 v2.7a key=value parser (HA)
  ))
  (/usr/local/texlive/2022/texmf-dist/tex/latex/fontspec/fontspec.sty
  (/usr/local/texlive/2022/texmf-dist/tex/latex/l3packages/xparse/xparse.sty
  (/usr/local/texlive/2022/texmf-dist/tex/latex/l3kernel/expl3.sty
  Package: expl3 2022-02-24 L3 programming layer (loader) 
  
  (/usr/local/texlive/2022/texmf-dist/tex/latex/l3backend/l3backend-luatex.def
  File: l3backend-luatex.def 2022-02-07 L3 backend support: PDF output (LuaTeX)
  \l__color_backend_stack_int=\count194
  \l__pdf_internal_box=\box52
  ))
  Package: xparse 2022-01-12 L3 Experimental document command parser
  )
  Package: fontspec 2022/01/15 v2.8a Font selection for XeLaTeX and LuaLaTeX
  Lua module: fontspec 2022/01/15 2.8a Font selection for XeLaTeX and LuaLaTeX (/
  usr/local/texlive/2022/texmf-dist/tex/latex/fontspec/fontspec-luatex.sty
  Package: fontspec-luatex 2022/01/15 v2.8a Font selection for XeLaTeX and LuaLaT
  eX
  \l__fontspec_script_int=\count195
  \l__fontspec_language_int=\count196
  \l__fontspec_strnum_int=\count197
  \l__fontspec_tmp_int=\count198
  \l__fontspec_tmpa_int=\count199
  \l__fontspec_tmpb_int=\count266
  \l__fontspec_tmpc_int=\count267
  \l__fontspec_em_int=\count268
  \l__fontspec_emdef_int=\count269
  \l__fontspec_strong_int=\count270
  \l__fontspec_strongdef_int=\count271
  \l__fontspec_tmpa_dim=\dimen138
  \l__fontspec_tmpb_dim=\dimen139
  \l__fontspec_tmpc_dim=\dimen140
  
  (/usr/local/texlive/2022/texmf-dist/tex/latex/base/fontenc.sty
  Package: fontenc 2021/04/29 v2.0v Standard LaTeX package
  )
  (/usr/local/texlive/2022/texmf-dist/tex/latex/fontspec/fontspec.cfg)))
  (/usr/local/texlive/2022/texmf-dist/tex/generic/iftex/iftex.sty
  Package: iftex 2022/02/03 v1.0f TeX engine tests
  )
  (/usr/local/texlive/2022/texmf-dist/tex/latex/l3packages/l3keys2e/l3keys2e.sty
  Package: l3keys2e 2022-01-12 LaTeX2e option processing using LaTeX3 keys
  ) (/usr/local/texlive/2022/texmf-dist/tex/luatex/luatexbase/luatexbase.sty
  Package: luatexbase 2015/10/04 v1.3 luatexbase interface to LuaTeX 
  
  (/usr/local/texlive/2022/texmf-dist/tex/luatex/ctablestack/ctablestack.sty
  Package: ctablestack 2015/10/01 v1.0 Catcode table stable support
  \@catcodetablestackcnt=\count272
  )
  \CatcodeTableOther=\catcodetable12
  \CatcodeTableExpl=\catcodetable13
  )
  Lua module: polyglossia 2013/05/11 1.3 Polyglossia
  (/home/mattes/texmf/tex/latex/polyglossia/gloss-latex.lde
  Package: gloss-latex 2021/07/10 vv1.53 polyglossia: module for default language
  
  The property list \polyglossia@langsetup contains the pairs (without outer
  braces):
  >  {latex/script}  =>  {latin}
  >  {latex/lcscript}  =>  {latin}
  >  {latex/scripttag}  =>  {}
  >  {latex/language}  =>  {Latex}
  >  {latex/langtag}  =>  {ENG}
  >  {latex/bcp47}  =>  {}
  >  {latex/hyphennames}  =>  {english}
  >  {latex/direction}  =>  {LR}
  >  {latex/hyphenmins}  =>  {2,3}
  >  {latex/frenchspacing}  =>  {false}
  >  {latex/indentfirst}  =>  {false}
  >  {latex/fontsetup}  =>  {true}
  >  {latex/envname}  =>  {latex}
  >  {latex/babelname}  =>  {latex}
  >  {latex/localnumeral}  =>  {polyglossia@C@localnumeral}
  >  {latex/Localnumeral}  =>  {polyglossia@C@localnumeral}
  >  {latex/DefineCommandsCmd}  =>  {use_none:n}.
  )
  Package polyglossia Info: Default language is latex.
  Package polyglossia Info: Setting LuaTeX font renderer to Harfbuzz.
  )
  (/home/mattes/texmf/tex/latex/polyglossia/gloss-english.ldf
  File: gloss-english.ldf polyglossia: module for english
  The property list \polyglossia@langsetup contains the pairs (without outer
  braces):
  >  {latex/script}  =>  {latin}
  >  {latex/lcscript}  =>  {latin}
  >  {latex/scripttag}  =>  {}
  >  {latex/language}  =>  {Latex}
  >  {latex/langtag}  =>  {ENG}
  >  {latex/bcp47}  =>  {}
  >  {latex/hyphennames}  =>  {english}
  >  {latex/direction}  =>  {LR}
  >  {latex/hyphenmins}  =>  {2,3}
  >  {latex/frenchspacing}  =>  {false}
  >  {latex/indentfirst}  =>  {false}
  >  {latex/fontsetup}  =>  {true}
  >  {latex/envname}  =>  {latex}
  >  {latex/babelname}  =>  {latex}
  >  {latex/localnumeral}  =>  {polyglossia@C@localnumeral}
  >  {latex/Localnumeral}  =>  {polyglossia@C@localnumeral}
  >  {latex/DefineCommandsCmd}  =>  {use_none:n}
  >  {english/script}  =>  {latin}
  >  {english/lcscript}  =>  {latin}
  >  {english/scripttag}  =>  {}
  >  {english/language}  =>  {English}
  >  {english/langtag}  =>  {ENG}
  >  {english/bcp47}  =>  {en-US}
  >  {english/hyphennames}  =>  {english,american,usenglish,USenglish}
  >  {english/direction}  =>  {LR}
  >  {english/hyphenmins}  =>  {2,3}
  >  {english/frenchspacing}  =>  {false}
  >  {english/indentfirst}  =>  {false}
  >  {english/fontsetup}  =>  {true}
  >  {english/envname}  =>  {english}
  >  {english/babelname}  =>  {english}
  >  {english/localnumeral}  =>  {polyglossia@C@localnumeral}
  >  {english/Localnumeral}  =>  {polyglossia@C@localnumeral}
  >  {english/DefineCommandsCmd}  =>  {xpg_define_language_commands:e}.
  Package polyglossia Info: Option: English, variant=american.
  )
  Package polyglossia Info: Default language is english.
  
  (/home/mattes/texmf/tex/latex/polyglossia/gloss-german.ldf
  File: gloss-german.ldf polyglossia: module for german
  The property list \polyglossia@langsetup contains the pairs (without outer
  braces):
  >  {latex/script}  =>  {latin}
  >  {latex/lcscript}  =>  {latin}
  >  {latex/scripttag}  =>  {}
  >  {latex/language}  =>  {Latex}
  >  {latex/langtag}  =>  {ENG}
  >  {latex/bcp47}  =>  {}
  >  {latex/hyphennames}  =>  {english}
  >  {latex/direction}  =>  {LR}
  >  {latex/hyphenmins}  =>  {2,3}
  >  {latex/frenchspacing}  =>  {false}
  >  {latex/indentfirst}  =>  {false}
  >  {latex/fontsetup}  =>  {true}
  >  {latex/envname}  =>  {latex}
  >  {latex/babelname}  =>  {latex}
  >  {latex/localnumeral}  =>  {polyglossia@C@localnumeral}
  >  {latex/Localnumeral}  =>  {polyglossia@C@localnumeral}
  >  {latex/DefineCommandsCmd}  =>  {use_none:n}
  >  {english/script}  =>  {latin}
  >  {english/lcscript}  =>  {latin}
  >  {english/scripttag}  =>  {}
  >  {english/language}  =>  {English}
  >  {english/langtag}  =>  {ENG}
  >  {english/bcp47}  =>  {en-US}
  >  {english/hyphennames}  =>  {english,american,usenglish,USenglish}
  >  {english/direction}  =>  {LR}
  >  {english/hyphenmins}  =>  {2,3}
  >  {english/frenchspacing}  =>  {false}
  >  {english/indentfirst}  =>  {false}
  >  {english/fontsetup}  =>  {true}
  >  {english/envname}  =>  {english}
  >  {english/babelname}  =>  {american}
  >  {english/localnumeral}  =>  {polyglossia@C@localnumeral}
  >  {english/Localnumeral}  =>  {polyglossia@C@localnumeral}
  >  {english/DefineCommandsCmd}  =>  {xpg_define_language_commands:e}
  >  {german/script}  =>  {latin}
  >  {german/lcscript}  =>  {latin}
  >  {german/scripttag}  =>  {}
  >  {german/language}  =>  {German}
  >  {german/langtag}  =>  {DEU}
  >  {german/bcp47}  =>  {de-DE}
  >  {german/hyphennames}  =>  {}
  >  {german/direction}  =>  {LR}
  >  {german/hyphenmins}  =>  {2,2}
  >  {german/frenchspacing}  =>  {true}
  >  {german/indentfirst}  =>  {false}
  >  {german/fontsetup}  =>  {true}
  >  {german/envname}  =>  {german}
  >  {german/babelname}  =>  {ngerman}
  >  {german/localnumeral}  =>  {polyglossia@C@localnumeral}
  >  {german/Localnumeral}  =>  {polyglossia@C@localnumeral}
  >  {german/DefineCommandsCmd}  =>  {xpg_define_language_commands:e}.
  Module polyglossia Info: Language data for german
  (polyglossia)            lefthyphenmin	2
  (polyglossia)            righthyphenmin	2
  (polyglossia)            patterns	hyph-de-1901.pat.txt
  (polyglossia)            hyphenation	
  (polyglossia)            synonyms	
  (polyglossia)            loader	loadhyph-de-1901.tex on input line 10
  Module polyglossia Info: Language german was not yet loaded; created with id 2 o
  n input line 10
  Package polyglossia Info: Option: German, spelling=new.
  Package polyglossia Info: Option: German, script=latin.
  Package polyglossia Info: Option: German, variant=german.
  Package polyglossia Info: Option: German, variant=german.
  Package polyglossia Info: Option: German, spelling=new.
  Package polyglossia Info: Option: German, script=latin.
  
  (/home/mattes/texmf/tex/latex/polyglossia/babelsh.def
  File: babelsh.def 2019/09/30 Babel common definitions for shorthands
  Taken verbatim from babel files (2019/09/27 v3.34)
  )
  Package polyglossia Info: Making " an active character on input line 177.
  ) (./output/mwe12.aux
  LaTeX Info: Redefining \rmfamily on input line 4.
  LaTeX Info: Redefining \sffamily on input line 4.
  LaTeX Info: Redefining \ttfamily on input line 4.
  LaTeX Info: Redefining \rmfamily on input line 8.
  LaTeX Info: Redefining \sffamily on input line 8.
  LaTeX Info: Redefining \ttfamily on input line 8.
  Module polyglossia Info: Language data for ngerman
  (polyglossia)            lefthyphenmin	2
  (polyglossia)            righthyphenmin	2
  (polyglossia)            patterns	hyph-de-1996.pat.txt
  (polyglossia)            hyphenation	
  (polyglossia)            synonyms	
  (polyglossia)            loader	loadhyph-de-1996.tex on input line 8
  Module polyglossia Info: Language ngerman was not yet loaded; created with id 3 
  on input line 8
  Package polyglossia Info: Option: German, variant=german.
  Package polyglossia Info: Option: German, spelling=new.
  Package polyglossia Info: Option: German, script=latin.
  Package polyglossia Info: Option: German, variant=german.
  Package polyglossia Info: Option: German, spelling=new.
  Package polyglossia Info: Option: German, script=latin.
  LaTeX Info: Redefining \rmfamily on input line 12.
  LaTeX Info: Redefining \sffamily on input line 12.
  LaTeX Info: Redefining \ttfamily on input line 12.
  Package polyglossia Info: Option: German, variant=german.
  Package polyglossia Info: Option: German, spelling=new.
  Package polyglossia Info: Option: German, script=latin.
  Package polyglossia Info: Option: German, variant=german.
  Package polyglossia Info: Option: German, spelling=new.
  Package polyglossia Info: Option: German, script=latin.
  LaTeX Info: Redefining \rmfamily on input line 16.
  LaTeX Info: Redefining \sffamily on input line 16.
  LaTeX Info: Redefining \ttfamily on input line 16.
  )
  \openout1 = mwe12.aux
  
  LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 6.
  LaTeX Font Info:    ... okay on input line 6.
  LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 6.
  LaTeX Font Info:    ... okay on input line 6.
  LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 6.
  LaTeX Font Info:    ... okay on input line 6.
  LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 6.
  LaTeX Font Info:    ... okay on input line 6.
  LaTeX Font Info:    Checking defaults for TS1/cmr/m/n on input line 6.
  LaTeX Font Info:    Trying to load font information for TS1+cmr on input line 6
  .
  
  (/usr/local/texlive/2022/texmf-dist/tex/latex/base/ts1cmr.fd
  File: ts1cmr.fd 2019/12/16 v2.5j Standard LaTeX font definitions
  )
  LaTeX Font Info:    ... okay on input line 6.
  LaTeX Font Info:    Checking defaults for TU/lmr/m/n on input line 6.
  LaTeX Font Info:    ... okay on input line 6.
  LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 6.
  LaTeX Font Info:    ... okay on input line 6.
  LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 6.
  LaTeX Font Info:    ... okay on input line 6.
  Package scrbase Info: activating english \contentsname on input line 6.
  Package scrbase Info: activating english \listfigurename on input line 6.
  Package scrbase Info: activating english \listtablename on input line 6.
  
  Package fontspec Info: Adjusting the maths setup (use [no-math] to avoid
  (fontspec)             this).
  
  \symlegacymaths=\mathgroup4
  LaTeX Font Info:    Overwriting symbol font `legacymaths' in version `bold'
  (Font)                  OT1/cmr/m/n --> OT1/cmr/bx/n on input line 6.
  LaTeX Font Info:    Redeclaring math accent \acute on input line 6.
  LaTeX Font Info:    Redeclaring math accent \grave on input line 6.
  LaTeX Font Info:    Redeclaring math accent \ddot on input line 6.
  LaTeX Font Info:    Redeclaring math accent \tilde on input line 6.
  LaTeX Font Info:    Redeclaring math accent \bar on input line 6.
  LaTeX Font Info:    Redeclaring math accent \breve on input line 6.
  LaTeX Font Info:    Redeclaring math accent \check on input line 6.
  LaTeX Font Info:    Redeclaring math accent \hat on input line 6.
  LaTeX Font Info:    Redeclaring math accent \dot on input line 6.
  LaTeX Font Info:    Redeclaring math accent \mathring on input line 6.
  LaTeX Font Info:    Redeclaring math symbol \colon on input line 6.
  LaTeX Font Info:    Redeclaring math symbol \Gamma on input line 6.
  LaTeX Font Info:    Redeclaring math symbol \Delta on input line 6.
  LaTeX Font Info:    Redeclaring math symbol \Theta on input line 6.
  LaTeX Font Info:    Redeclaring math symbol \Lambda on input line 6.
  LaTeX Font Info:    Redeclaring math symbol \Xi on input line 6.
  LaTeX Font Info:    Redeclaring math symbol \Pi on input line 6.
  LaTeX Font Info:    Redeclaring math symbol \Sigma on input line 6.
  LaTeX Font Info:    Redeclaring math symbol \Upsilon on input line 6.
  LaTeX Font Info:    Redeclaring math symbol \Phi on input line 6.
  LaTeX Font Info:    Redeclaring math symbol \Psi on input line 6.
  LaTeX Font Info:    Redeclaring math symbol \Omega on input line 6.
  LaTeX Font Info:    Redeclaring math symbol \mathdollar on input line 6.
  LaTeX Font Info:    Redeclaring symbol font `operators' on input line 6.
  LaTeX Font Info:    Encoding `OT1' has changed to `TU' for symbol font
  (Font)              `operators' in the math version `normal' on input line 6.
  LaTeX Font Info:    Overwriting symbol font `operators' in version `normal'
  (Font)                  OT1/cmr/m/n --> TU/lmr/m/n on input line 6.
  LaTeX Font Info:    Encoding `OT1' has changed to `TU' for symbol font
  (Font)              `operators' in the math version `bold' on input line 6.
  LaTeX Font Info:    Overwriting symbol font `operators' in version `bold'
  (Font)                  OT1/cmr/bx/n --> TU/lmr/m/n on input line 6.
  LaTeX Font Info:    Overwriting symbol font `operators' in version `normal'
  (Font)                  TU/lmr/m/n --> TU/lmr/m/n on input line 6.
  LaTeX Font Info:    Overwriting math alphabet `\mathit' in version `normal'
  (Font)                  OT1/cmr/m/it --> TU/lmr/m/it on input line 6.
  LaTeX Font Info:    Overwriting math alphabet `\mathbf' in version `normal'
  (Font)                  OT1/cmr/bx/n --> TU/lmr/b/n on input line 6.
  LaTeX Font Info:    Overwriting math alphabet `\mathsf' in version `normal'
  (Font)                  OT1/cmss/m/n --> TU/lmss/m/n on input line 6.
  LaTeX Font Info:    Overwriting math alphabet `\mathtt' in version `normal'
  (Font)                  OT1/cmtt/m/n --> TU/lmtt/m/n on input line 6.
  LaTeX Font Info:    Overwriting symbol font `operators' in version `bold'
  (Font)                  TU/lmr/m/n --> TU/lmr/b/n on input line 6.
  LaTeX Font Info:    Overwriting math alphabet `\mathit' in version `bold'
  (Font)                  OT1/cmr/bx/it --> TU/lmr/b/it on input line 6.
  LaTeX Font Info:    Overwriting math alphabet `\mathsf' in version `bold'
  (Font)                  OT1/cmss/bx/n --> TU/lmss/b/n on input line 6.
  LaTeX Font Info:    Overwriting math alphabet `\mathtt' in version `bold'
  (Font)                  OT1/cmtt/m/n --> TU/lmtt/b/n on input line 6.
  The property list \__xpg_alias contains the pairs (without outer braces):
  >  {latex/target}  =>  {latex}
  >  {english/target}  =>  {english}
  >  {en/target}  =>  {english}
  >  {en/bcp47}  =>  {en}
  >  {en/options}  =>  {bcp47=en}
  >  {en-AU/target}  =>  {en}
  >  {en-AU/variant}  =>  {australian}
  >  {en-AU/bcp47}  =>  {en-AU}
  >  {en-AU/babelname}  =>  {australian}
  >  {en-AU/options}  =>  {variant=australian,babelname=autralian,bcp47=en-AU}
  >  {en-CA/target}  =>  {en}
  >  {en-CA/variant}  =>  {canadian}
  >  {en-CA/bcp47}  =>  {en-CA}
  >  {en-CA/babelname}  =>  {canadian}
  >  {en-CA/options}  =>  {variant=canadian,babelname=canadian,bcp47=en-CA}
  >  {en-GB/target}  =>  {en}
  >  {en-GB/variant}  =>  {british}
  >  {en-GB/bcp47}  =>  {en-NZ}
  >  {en-GB/babelname}  =>  {british}
  >  {en-GB/options}  =>  {variant=british,babelname=british,bcp47=en-NZ}
  >  {en-NZ/target}  =>  {en}
  >  {en-NZ/variant}  =>  {newzealand}
  >  {en-NZ/bcp47}  =>  {en-NZ}
  >  {en-NZ/babelname}  =>  {newzealand}
  >  {en-NZ/options}  =>  {variant=newzealand,babelname=newzealand,bcp47=en-NZ}
  >  {en-US/target}  =>  {en}
  >  {en-US/variant}  =>  {us}
  >  {en-US/bcp47}  =>  {en-US}
  >  {en-US/babelname}  =>  {us}
  >  {en-US/options}  =>  {variant=us,babelname=american,bcp47=en-US}
  >  {american/target}  =>  {en-US}
  >  {american/variant}  =>  {us}
  >  {american/options}  =>  {variant=us}
  >  {australian/target}  =>  {en-AU}
  >  {australian/variant}  =>  {australian}
  >  {australian/options}  =>  {variant=australian}
  >  {british/target}  =>  {en-GB}
  >  {british/variant}  =>  {british}
  >  {british/options}  =>  {variant=british}
  >  {canadian/target}  =>  {en-CA}
  >  {canadian/variant}  =>  {canadian}
  >  {canadian/options}  =>  {variant=canadian}
  >  {newzealand/target}  =>  {en-NZ}
  >  {newzealand/variant}  =>  {newzealand}
  >  {newzealand/options}  =>  {variant=newzealand}
  >  {german/target}  =>  {german}
  >  {de/target}  =>  {german}
  >  {de-CH/target}  =>  {german}
  >  {de-CH/variant}  =>  {swiss}
  >  {de-CH/options}  =>  {variant=swiss,spelling=new}
  >  {de-AT/target}  =>  {german}
  >  {de-AT/variant}  =>  {austrian}
  >  {de-AT/options}  =>  {variant=austrian,spelling=new}
  >  {de-DE/target}  =>  {german}
  >  {de-DE/variant}  =>  {german}
  >  {de-DE/options}  =>  {variant=german,spelling=new}
  >  {de-Latf-CH/target}  =>  {german}
  >  {de-Latf-CH/variant}  =>  {swiss}
  >  {de-Latf-CH/options}  =>  {variant=swiss,spelling=new,script=blackletter}
  >  {de-Latf-DE/target}  =>  {german}
  >  {de-Latf-DE/variant}  =>  {german}
  >  {de-Latf-DE/options}  =>  {variant=german,spelling=new,script=blackletter}
  >  {de-Latf-AT/target}  =>  {german}
  >  {de-Latf-AT/variant}  =>  {austrian}
  >  {de-Latf-AT/options}  => 
  {variant=austrian,spelling=new,script=blackletter}
  >  {de-AT-1901/target}  =>  {german}
  >  {de-AT-1901/variant}  =>  {austrian}
  >  {de-AT-1901/options}  =>  {variant=austrian,spelling=old}
  >  {de-CH-1996/target}  =>  {german}
  >  {de-CH-1996/variant}  =>  {swiss}
  >  {de-CH-1996/options}  =>  {variant=swiss,spelling=new}
  >  {de-AT-1996/target}  =>  {german}
  >  {de-AT-1996/variant}  =>  {austrian}
  >  {de-AT-1996/options}  =>  {variant=austrian,spelling=new}
  >  {de-DE-1901/target}  =>  {german}
  >  {de-DE-1901/variant}  =>  {german}
  >  {de-DE-1901/options}  =>  {variant=german,spelling=old}
  >  {de-Latf-CH-1901/target}  =>  {german}
  >  {de-Latf-CH-1901/variant}  =>  {swiss}
  >  {de-Latf-CH-1901/options}  => 
  {variant=swiss,spelling=old,script=blackletter}
  >  {de-CH-1901/target}  =>  {german}
  >  {de-CH-1901/variant}  =>  {swiss}
  >  {de-CH-1901/options}  =>  {variant=swiss,spelling=old}
  >  {de-Latf-AT-1901/target}  =>  {german}
  >  {de-Latf-AT-1901/variant}  =>  {austrian}
  >  {de-Latf-AT-1901/options}  => 
  {variant=austrian,spelling=old,script=blackletter}
  >  {de-Latf-CH-1996/target}  =>  {german}
  >  {de-Latf-CH-1996/variant}  =>  {swiss}
  >  {de-Latf-CH-1996/options}  => 
  {variant=swiss,spelling=new,script=blackletter}
  >  {de-Latf/target}  =>  {german}
  >  {de-Latf/options}  =>  {script=blackletter}
  >  {de-DE-1996/target}  =>  {german}
  >  {de-DE-1996/variant}  =>  {german}
  >  {de-DE-1996/options}  =>  {variant=german,spelling=new}
  >  {de-Latf-DE-1901/target}  =>  {german}
  >  {de-Latf-DE-1901/variant}  =>  {german}
  >  {de-Latf-DE-1901/options}  => 
  {variant=german,spelling=old,script=blackletter}
  >  {de-Latf-DE-1996/target}  =>  {german}
  >  {de-Latf-DE-1996/variant}  =>  {german}
  >  {de-Latf-DE-1996/options}  => 
  {variant=german,spelling=new,script=blackletter}
  >  {de-Latf-AT-1996/target}  =>  {german}
  >  {de-Latf-AT-1996/variant}  =>  {austrian}
  >  {de-Latf-AT-1996/options}  => 
  {variant=austrian,spelling=new,script=blackletter}
  >  {austrian/target}  =>  {german}
  >  {austrian/variant}  =>  {austrian}
  >  {austrian/options}  =>  {variant=austrian,spelling=old}
  >  {naustrian/target}  =>  {german}
  >  {naustrian/variant}  =>  {austrian}
  >  {naustrian/options}  =>  {variant=austrian,spelling=new}
  >  {germanb/target}  =>  {german}
  >  {germanb/variant}  =>  {german}
  >  {germanb/options}  =>  {variant=german,spelling=old}
  >  {ngerman/target}  =>  {german}
  >  {ngerman/variant}  =>  {german}
  >  {ngerman/options}  =>  {variant=german,spelling=new}
  >  {swissgerman/target}  =>  {german}
  >  {swissgerman/variant}  =>  {swiss}
  >  {swissgerman/options}  =>  {variant=swiss,spelling=old}
  >  {nswissgerman/target}  =>  {german}
  >  {nswissgerman/variant}  =>  {swiss}
  >  {nswissgerman/options}  =>  {variant=swiss,spelling=new}.
  LaTeX Info: Redefining \rmfamily on input line 6.
  LaTeX Info: Redefining \sffamily on input line 6.
  LaTeX Info: Redefining \ttfamily on input line 6.
  LaTeX Info: Redefining \rmfamily on input line 11.
  LaTeX Info: Redefining \sffamily on input line 11.
  LaTeX Info: Redefining \ttfamily on input line 11.
  Module polyglossia Info: Language ngerman already loaded; id is 3 on input line 
  11
  LaTeX Info: Redefining \rmfamily on input line 13.
  LaTeX Info: Redefining \sffamily on input line 13.
  LaTeX Info: Redefining \ttfamily on input line 13.
  Module polyglossia Info: Language ngerman already loaded; id is 3 on input line 
  13
  LaTeX Info: Redefining \rmfamily on input line 15.
  LaTeX Info: Redefining \sffamily on input line 15.
  LaTeX Info: Redefining \ttfamily on input line 15.
  Module polyglossia Info: Language ngerman already loaded; id is 3 on input line 
  15
  LaTeX Info: Redefining \rmfamily on input line 17.
  LaTeX Info: Redefining \sffamily on input line 17.
  LaTeX Info: Redefining \ttfamily on input line 17.
  
  ! Undefined control sequence.
  \\foreignlanguage ...>\__xpg_foreignlanguage:eeen 
                                                  {#1}{#2}{\xpg_alias_base_l...
  l.20 ...n}{Dies ist ein Test von Problem-""Nr. 537.}
                                                  
  The control sequence at the end of the top line
  of your error message was never \def'ed. If you have
  misspelled it (e.g., `\hobx'), type `I' and the correct
  spelling (e.g., `I\hbox'). Otherwise just continue,
  and I'll forget about whatever was undefined.
  
  The property list \polyglossia@langsetup contains the pairs (without outer
  braces):
  >  {latex/script}  =>  {latin}
  >  {latex/lcscript}  =>  {latin}
  >  {latex/scripttag}  =>  {}
  >  {latex/language}  =>  {Latex}
  >  {latex/langtag}  =>  {ENG}
  >  {latex/bcp47}  =>  {}
  >  {latex/hyphennames}  =>  {english}
  >  {latex/direction}  =>  {LR}
  >  {latex/hyphenmins}  =>  {2,3}
  >  {latex/frenchspacing}  =>  {false}
  >  {latex/indentfirst}  =>  {false}
  >  {latex/fontsetup}  =>  {true}
  >  {latex/envname}  =>  {latex}
  >  {latex/babelname}  =>  {latex}
  >  {latex/localnumeral}  =>  {polyglossia@C@localnumeral}
  >  {latex/Localnumeral}  =>  {polyglossia@C@localnumeral}
  >  {latex/DefineCommandsCmd}  =>  {use_none:n}
  >  {english/script}  =>  {latin}
  >  {english/lcscript}  =>  {latin}
  >  {english/scripttag}  =>  {}
  >  {english/language}  =>  {English}
  >  {english/langtag}  =>  {ENG}
  >  {english/bcp47}  =>  {en-US}
  >  {english/hyphennames}  =>  {english,american,usenglish,USenglish}
  >  {english/direction}  =>  {LR}
  >  {english/hyphenmins}  =>  {2,3}
  >  {english/frenchspacing}  =>  {false}
  >  {english/indentfirst}  =>  {false}
  >  {english/fontsetup}  =>  {true}
  >  {english/envname}  =>  {english}
  >  {english/babelname}  =>  {american}
  >  {english/localnumeral}  =>  {polyglossia@C@localnumeral}
  >  {english/Localnumeral}  =>  {polyglossia@C@localnumeral}
  >  {english/DefineCommandsCmd}  =>  {xpg_define_language_commands:e}
  >  {german/script}  =>  {latin}
  >  {german/lcscript}  =>  {latin}
  >  {german/scripttag}  =>  {}
  >  {german/language}  =>  {German}
  >  {german/langtag}  =>  {DEU}
  >  {german/bcp47}  =>  {de-DE}
  >  {german/hyphennames}  =>  {}
  >  {german/direction}  =>  {LR}
  >  {german/hyphenmins}  =>  {2,2}
  >  {german/frenchspacing}  =>  {true}
  >  {german/indentfirst}  =>  {false}
  >  {german/fontsetup}  =>  {true}
  >  {german/envname}  =>  {german}
  >  {german/babelname}  =>  {ngerman}
  >  {german/localnumeral}  =>  {polyglossia@C@localnumeral}
  >  {german/Localnumeral}  =>  {polyglossia@C@localnumeral}
  >  {german/DefineCommandsCmd}  =>  {xpg_define_language_commands:e}.
  The property list \__xpg_alias contains the pairs (without outer braces):
  >  {latex/target}  =>  {latex}
  >  {english/target}  =>  {english}
  >  {en/target}  =>  {english}
  >  {en/bcp47}  =>  {en}
  >  {en/options}  =>  {bcp47=en}
  >  {en-AU/target}  =>  {en}
  >  {en-AU/variant}  =>  {australian}
  >  {en-AU/bcp47}  =>  {en-AU}
  >  {en-AU/babelname}  =>  {australian}
  >  {en-AU/options}  =>  {variant=australian,babelname=autralian,bcp47=en-AU}
  >  {en-CA/target}  =>  {en}
  >  {en-CA/variant}  =>  {canadian}
  >  {en-CA/bcp47}  =>  {en-CA}
  >  {en-CA/babelname}  =>  {canadian}
  >  {en-CA/options}  =>  {variant=canadian,babelname=canadian,bcp47=en-CA}
  >  {en-GB/target}  =>  {en}
  >  {en-GB/variant}  =>  {british}
  >  {en-GB/bcp47}  =>  {en-NZ}
  >  {en-GB/babelname}  =>  {british}
  >  {en-GB/options}  =>  {variant=british,babelname=british,bcp47=en-NZ}
  >  {en-NZ/target}  =>  {en}
  >  {en-NZ/variant}  =>  {newzealand}
  >  {en-NZ/bcp47}  =>  {en-NZ}
  >  {en-NZ/babelname}  =>  {newzealand}
  >  {en-NZ/options}  =>  {variant=newzealand,babelname=newzealand,bcp47=en-NZ}
  >  {en-US/target}  =>  {en}
  >  {en-US/variant}  =>  {us}
  >  {en-US/bcp47}  =>  {en-US}
  >  {en-US/babelname}  =>  {us}
  >  {en-US/options}  =>  {variant=us,babelname=american,bcp47=en-US}
  >  {american/target}  =>  {en-US}
  >  {american/variant}  =>  {us}
  >  {american/options}  =>  {variant=us}
  >  {australian/target}  =>  {en-AU}
  >  {australian/variant}  =>  {australian}
  >  {australian/options}  =>  {variant=australian}
  >  {british/target}  =>  {en-GB}
  >  {british/variant}  =>  {british}
  >  {british/options}  =>  {variant=british}
  >  {canadian/target}  =>  {en-CA}
  >  {canadian/variant}  =>  {canadian}
  >  {canadian/options}  =>  {variant=canadian}
  >  {newzealand/target}  =>  {en-NZ}
  >  {newzealand/variant}  =>  {newzealand}
  >  {newzealand/options}  =>  {variant=newzealand}
  >  {german/target}  =>  {german}
  >  {de/target}  =>  {german}
  >  {de-CH/target}  =>  {german}
  >  {de-CH/variant}  =>  {swiss}
  >  {de-CH/options}  =>  {variant=swiss,spelling=new}
  >  {de-AT/target}  =>  {german}
  >  {de-AT/variant}  =>  {austrian}
  >  {de-AT/options}  =>  {variant=austrian,spelling=new}
  >  {de-DE/target}  =>  {german}
  >  {de-DE/variant}  =>  {german}
  >  {de-DE/options}  =>  {variant=german,spelling=new}
  >  {de-Latf-CH/target}  =>  {german}
  >  {de-Latf-CH/variant}  =>  {swiss}
  >  {de-Latf-CH/options}  =>  {variant=swiss,spelling=new,script=blackletter}
  >  {de-Latf-DE/target}  =>  {german}
  >  {de-Latf-DE/variant}  =>  {german}
  >  {de-Latf-DE/options}  =>  {variant=german,spelling=new,script=blackletter}
  >  {de-Latf-AT/target}  =>  {german}
  >  {de-Latf-AT/variant}  =>  {austrian}
  >  {de-Latf-AT/options}  => 
  {variant=austrian,spelling=new,script=blackletter}
  >  {de-AT-1901/target}  =>  {german}
  >  {de-AT-1901/variant}  =>  {austrian}
  >  {de-AT-1901/options}  =>  {variant=austrian,spelling=old}
  >  {de-CH-1996/target}  =>  {german}
  >  {de-CH-1996/variant}  =>  {swiss}
  >  {de-CH-1996/options}  =>  {variant=swiss,spelling=new}
  >  {de-AT-1996/target}  =>  {german}
  >  {de-AT-1996/variant}  =>  {austrian}
  >  {de-AT-1996/options}  =>  {variant=austrian,spelling=new}
  >  {de-DE-1901/target}  =>  {german}
  >  {de-DE-1901/variant}  =>  {german}
  >  {de-DE-1901/options}  =>  {variant=german,spelling=old}
  >  {de-Latf-CH-1901/target}  =>  {german}
  >  {de-Latf-CH-1901/variant}  =>  {swiss}
  >  {de-Latf-CH-1901/options}  => 
  {variant=swiss,spelling=old,script=blackletter}
  >  {de-CH-1901/target}  =>  {german}
  >  {de-CH-1901/variant}  =>  {swiss}
  >  {de-CH-1901/options}  =>  {variant=swiss,spelling=old}
  >  {de-Latf-AT-1901/target}  =>  {german}
  >  {de-Latf-AT-1901/variant}  =>  {austrian}
  >  {de-Latf-AT-1901/options}  => 
  {variant=austrian,spelling=old,script=blackletter}
  >  {de-Latf-CH-1996/target}  =>  {german}
  >  {de-Latf-CH-1996/variant}  =>  {swiss}
  >  {de-Latf-CH-1996/options}  => 
  {variant=swiss,spelling=new,script=blackletter}
  >  {de-Latf/target}  =>  {german}
  >  {de-Latf/options}  =>  {script=blackletter}
  >  {de-DE-1996/target}  =>  {german}
  >  {de-DE-1996/variant}  =>  {german}
  >  {de-DE-1996/options}  =>  {variant=german,spelling=new}
  >  {de-Latf-DE-1901/target}  =>  {german}
  >  {de-Latf-DE-1901/variant}  =>  {german}
  >  {de-Latf-DE-1901/options}  => 
  {variant=german,spelling=old,script=blackletter}
  >  {de-Latf-DE-1996/target}  =>  {german}
  >  {de-Latf-DE-1996/variant}  =>  {german}
  >  {de-Latf-DE-1996/options}  => 
  {variant=german,spelling=new,script=blackletter}
  >  {de-Latf-AT-1996/target}  =>  {german}
  >  {de-Latf-AT-1996/variant}  =>  {austrian}
  >  {de-Latf-AT-1996/options}  => 
  {variant=austrian,spelling=new,script=blackletter}
  >  {austrian/target}  =>  {german}
  >  {austrian/variant}  =>  {austrian}
  >  {austrian/options}  =>  {variant=austrian,spelling=old}
  >  {naustrian/target}  =>  {german}
  >  {naustrian/variant}  =>  {austrian}
  >  {naustrian/options}  =>  {variant=austrian,spelling=new}
  >  {germanb/target}  =>  {german}
  >  {germanb/variant}  =>  {german}
  >  {germanb/options}  =>  {variant=german,spelling=old}
  >  {ngerman/target}  =>  {german}
  >  {ngerman/variant}  =>  {german}
  >  {ngerman/options}  =>  {variant=german,spelling=new}
  >  {swissgerman/target}  =>  {german}
  >  {swissgerman/variant}  =>  {swiss}
  >  {swissgerman/options}  =>  {variant=swiss,spelling=old}
  >  {nswissgerman/target}  =>  {german}
  >  {nswissgerman/variant}  =>  {swiss}
  >  {nswissgerman/options}  =>  {variant=swiss,spelling=new}.
  [1
  
  {/usr/local/texlive/2022/texmf-var/fonts/map/pdftex/updmap/pdftex.map}]
  (./output/mwe12.aux
  LaTeX Info: Redefining \rmfamily on input line 4.
  LaTeX Info: Redefining \sffamily on input line 4.
  LaTeX Info: Redefining \ttfamily on input line 4.
  LaTeX Info: Redefining \rmfamily on input line 8.
  LaTeX Info: Redefining \sffamily on input line 8.
  LaTeX Info: Redefining \ttfamily on input line 8.
  Module polyglossia Info: Language ngerman already loaded; id is 3 on input line 
  8
  Package polyglossia Info: Option: German, variant=german.
  Package polyglossia Info: Option: German, spelling=new.
  Package polyglossia Info: Option: German, script=latin.
  Package polyglossia Info: Option: German, variant=german.
  Package polyglossia Info: Option: German, spelling=new.
  Package polyglossia Info: Option: German, script=latin.
  LaTeX Info: Redefining \rmfamily on input line 12.
  LaTeX Info: Redefining \sffamily on input line 12.
  LaTeX Info: Redefining \ttfamily on input line 12.
  Package polyglossia Info: Option: German, variant=german.
  Package polyglossia Info: Option: German, spelling=new.
  Package polyglossia Info: Option: German, script=latin.
  Package polyglossia Info: Option: German, variant=german.
  Package polyglossia Info: Option: German, spelling=new.
  Package polyglossia Info: Option: German, script=latin.
  LaTeX Info: Redefining \rmfamily on input line 16.
  LaTeX Info: Redefining \sffamily on input line 16.
  LaTeX Info: Redefining \ttfamily on input line 16.
  ))
  
  Here is how much of LuaTeX's memory you used:
  7607 strings out of 477785
  100000,794899 words of node,token memory allocated
  426 words of node memory still in use:
   3 hlist, 1 vlist, 1 rule, 2 glue, 3 kern, 1 glyph, 4 attribute, 52 glue_spec,
  4 attribute_list, 1 write nodes
   avail lists: 1:2,2:95,3:44,4:1,5:34,6:10,7:494,9:40,11:10
  28149 multiletter control sequences out of 65536+600000
  16 fonts using 855119 bytes
  108i,7n,100p,10669b,383s stack positions out of 10000i,1000n,20000p,200000b,200000s
  </usr/local/texlive/2022/texmf-dist/fonts/opentype/public/lm/lmroman10-regular.o
  tf>
  Output written on mwe12.pdf (1 page, 5423 bytes).
  
  PDF statistics: 15 PDF objects out of 1000 (max. 8388607)
  8 compressed objects within 1 object stream
  0 named destinations out of 1000 (max. 131072)
  1 words of extra memory for PDF output out of 10000 (max. 100000000)
  ```
  
</details>

**Comment by moewew** [comment]
I don't think I understand the difference between an `.lde` and an `.ldf` file, but it is a bit confusing that the (original) warning message complains about an `.ldf` file missing (`File gloss-latex.ldf does not exist!`) when in actual fact we're missing an `.lde` file (`gloss-latex.lde`).

@maaattes Your problem appears unrelated, I can reproduce it with v1.54 as well.

**Comment by jspitz** [comment]
> Sorry, but I'm still having some issues. Using `polyglossia` 2022/04/09 v1.55.

This is unreleated to the problem reported here. Please file a new ticket.

**Comment by jspitz** [comment]
> I don't think I understand the difference between an `.lde` and an `.ldf` file, but it is a bit confusing that the (original) warning message complains about an `.ldf` file missing (`File gloss-latex.ldf does not exist!`) when in actual fact we're missing an `.lde` file (`gloss-latex.lde`).

This `lde` thing is unfinished work from @bastien-roucaries AFAIU. I am not going to delve deeply into this, only cleaning up.

**Comment by jspitz** [comment]
> it is a bit confusing that the (original) warning message complains about an `.ldf` file missing (`File gloss-latex.ldf does not exist!`) when in actual fact we're missing an `.lde` file (`gloss-latex.lde`).

Alas, we do not know at this point which format is expected (`polyglossia` searches for both starting with `*.lde`). But I have adapted the warning and now it also mentions this format.
